-- Fix: orders could be placed for out-of-stock items, driving inventory negative.
--
-- Root cause: create_order_with_items() (supabase_atomic_order.sql) inserted the
-- order + order_items with NO inventory check at all. Stock was only checked in
-- the browser (MenuItem.jsx / ManualOrderModal.jsx) and then deducted via a
-- SEPARATE, later RPC call (deduct_inventory_and_log) from OrderContext.jsx /
-- ManualOrderModal.jsx, explicitly treated as "non-fatal" on failure. That left
-- two independent races:
--   1. Client-side stock display can be stale; nothing server-side re-checked it
--      before the order row was created.
--   2. Two concurrent orders for the last unit could both pass the check-then-act
--      deduction, both succeed, and push available_quantity below zero.
--
-- Fix: move the stock check AND the deduction into the SAME transaction as the
-- order insert, using `SELECT ... FOR UPDATE` to lock the inventory row before
-- checking quantity. If any ingredient is insufficient, RAISE EXCEPTION rolls
-- back the entire transaction (order + order_items + any partial deduction) —
-- so an out-of-stock order is never created, and concurrent orders for the same
-- item serialize on the row lock instead of racing.
--
-- Run this in Supabase Dashboard -> SQL Editor. This REPLACES the function from
-- supabase_atomic_order.sql (same name/signature plus one new optional arg).
-- Apply during low-traffic hours; it changes behavior for every order placed
-- immediately after CREATE OR REPLACE runs (old in-flight requests already
-- committed are unaffected).

CREATE OR REPLACE FUNCTION create_order_with_items(
  p_user_id UUID,
  p_order_amount NUMERIC,
  p_status TEXT DEFAULT 'pending',
  p_notes TEXT DEFAULT NULL,
  p_items JSONB DEFAULT '[]'::jsonb,
  p_created_by TEXT DEFAULT NULL
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_order RECORD;
  v_order_items JSON;
  v_req RECORD;
  v_current_qty NUMERIC;
BEGIN
  -- Insert order (custom_order_id is auto-generated by existing trigger)
  INSERT INTO orders (user_id, order_amount, status, notes)
  VALUES (p_user_id, p_order_amount, p_status, p_notes)
  RETURNING * INTO v_order;

  -- Insert order items from the JSONB array
  IF jsonb_array_length(p_items) > 0 THEN
    INSERT INTO order_items (order_id, item_name, quantity, price)
    SELECT
      v_order.id,
      item->>'item_name',
      (item->>'quantity')::INTEGER,
      (item->>'price')::NUMERIC
    FROM jsonb_array_elements(p_items) AS item;
  END IF;

  -- Aggregate ingredient requirements across all ordered menu items, then lock
  -- + check + deduct each inventory row in a single deterministic order
  -- (ascending inventory_item_id) to avoid deadlocks between concurrent orders
  -- that share ingredients.
  FOR v_req IN
    SELECT mii.inventory_item_id AS inv_id,
           SUM(mii.quantity * (item->>'quantity')::NUMERIC) AS needed_qty
    FROM jsonb_array_elements(p_items) AS item
    JOIN menu_item_ingredients mii
      ON mii.menu_item_id = (item->>'menu_item_id')::INTEGER
    WHERE item ? 'menu_item_id' AND item->>'menu_item_id' IS NOT NULL
    GROUP BY mii.inventory_item_id
    ORDER BY mii.inventory_item_id
  LOOP
    SELECT available_quantity INTO v_current_qty
    FROM inventory
    WHERE id = v_req.inv_id
    FOR UPDATE;

    IF v_current_qty IS NULL THEN
      RAISE EXCEPTION 'Inventory item % not found', v_req.inv_id;
    END IF;

    IF v_current_qty < v_req.needed_qty THEN
      RAISE EXCEPTION 'Insufficient stock for inventory item % (available: %, required: %)',
        v_req.inv_id, v_current_qty, v_req.needed_qty;
    END IF;

    UPDATE inventory
    SET available_quantity = available_quantity - v_req.needed_qty,
        last_updated_on = now()
    WHERE id = v_req.inv_id;

    INSERT INTO inventory_ledger (
      inventory_item_id, item_code, item_name, transaction_type,
      quantity_change, quantity_before, quantity_after,
      reference_type, reference_id, notes, created_by
    )
    SELECT
      i.id, i.item_code, i.item_name, 'order_deduction',
      -v_req.needed_qty, v_current_qty, v_current_qty - v_req.needed_qty,
      'order', v_order.custom_order_id, NULL, p_created_by
    FROM inventory i
    WHERE i.id = v_req.inv_id;
  END LOOP;

  -- Fetch the inserted items to return them
  SELECT json_agg(oi) INTO v_order_items
  FROM order_items oi
  WHERE oi.order_id = v_order.id;

  -- Return the order with its items
  RETURN json_build_object(
    'order', row_to_json(v_order),
    'order_items', COALESCE(v_order_items, '[]'::json)
  );
END;
$$;

-- Production already has items pushed negative by this bug (confirmed via
-- live read: "Yoga bar 65" id=12 at -3, "Dahi" id=36 at -1, as of 2026-08-10).
-- Clamp those to 0 and log the correction to the ledger before adding the
-- constraint below, otherwise the ALTER TABLE will fail on existing rows.
-- Review these two items' real counted stock before/instead of trusting the
-- clamp-to-0 default.
INSERT INTO inventory_ledger (
  inventory_item_id, item_code, item_name, transaction_type,
  quantity_change, quantity_before, quantity_after,
  reference_type, reference_id, notes, created_by
)
SELECT
  id, item_code, item_name, 'manual_adjustment',
  -available_quantity, available_quantity, 0,
  'manual', NULL, 'Auto-clamp: negative stock correction (out-of-stock ordering bug)', 'system'
FROM inventory
WHERE available_quantity < 0;

UPDATE inventory SET available_quantity = 0 WHERE available_quantity < 0;

-- Defense in depth: never allow available_quantity to go negative even if some
-- other code path (manual edit, a future bug) tries to push it below zero.
ALTER TABLE inventory
  ADD CONSTRAINT inventory_available_quantity_non_negative
  CHECK (available_quantity >= 0);
