-- Atomic Order Creation RPC Function
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor → New Query)
-- This wraps order + order_items creation in a single transaction
-- so they either both succeed or both roll back.

CREATE OR REPLACE FUNCTION create_order_with_items(
  p_user_id UUID,
  p_order_amount NUMERIC,
  p_status TEXT DEFAULT 'pending',
  p_notes TEXT DEFAULT NULL,
  p_items JSONB DEFAULT '[]'::jsonb
)
RETURNS JSON
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_order RECORD;
  v_order_items JSON;
BEGIN
  -- Insert order (custom_order_id is auto-generated by existing trigger)
  INSERT INTO orders (user_id, order_amount, status, notes)
  VALUES (p_user_id, p_order_amount, p_status, p_notes)
  RETURNING * INTO v_order;

  -- Insert order items from the JSONB array
  IF jsonb_array_length(p_items) > 0 THEN
    INSERT INTO order_items (order_id, item_name, quantity, price)
    SELECT
      v_order.id,
      item->>'item_name',
      (item->>'quantity')::INTEGER,
      (item->>'price')::NUMERIC
    FROM jsonb_array_elements(p_items) AS item;
  END IF;

  -- Fetch the inserted items to return them
  SELECT json_agg(oi) INTO v_order_items
  FROM order_items oi
  WHERE oi.order_id = v_order.id;

  -- Return the order with its items
  RETURN json_build_object(
    'order', row_to_json(v_order),
    'order_items', COALESCE(v_order_items, '[]'::json)
  );
END;
$$;
