import { supabase } from './supabaseService'

export const inventoryService = {
  // Get all inventory items
  async getAllInventoryItems() {
    try {
      const { data, error } = await supabase
        .from('inventory')
        .select('*')
        .order('item_name', { ascending: true })

      if (error) return { success: false, error: error.message }
      return { success: true, items: data || [] }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Add a new inventory item
  async addInventoryItem(item) {
    try {
      const { data, error } = await supabase
        .from('inventory')
        .insert([{
          item_name: item.item_name.trim(),
          available_quantity: parseFloat(item.available_quantity) || 0,
          uom: item.uom.trim() || 'pcs'
          // item_code is auto-generated by DB trigger
        }])
        .select()
        .single()

      if (error) return { success: false, error: error.message }
      return { success: true, item: data }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Update an inventory item
  async updateInventoryItem(id, updates) {
    try {
      const updateData = {}
      if (updates.item_name !== undefined) updateData.item_name = updates.item_name.trim()
      if (updates.available_quantity !== undefined) updateData.available_quantity = parseFloat(updates.available_quantity) || 0
      if (updates.uom !== undefined) updateData.uom = updates.uom.trim()

      const { data, error } = await supabase
        .from('inventory')
        .update(updateData)
        .eq('id', id)
        .select()
        .single()

      if (error) return { success: false, error: error.message }
      return { success: true, item: data }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Delete an inventory item
  async deleteInventoryItem(id) {
    try {
      const { error } = await supabase
        .from('inventory')
        .delete()
        .eq('id', id)

      if (error) return { success: false, error: error.message }
      return { success: true }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Deduct quantities for ordered items (called after successful order placement)
  // items: [{ inventory_item_id, quantity }]
  // referenceId: custom_order_id of the order (e.g. "ORD123456")
  // createdBy: name of the user who placed the order
  async deductInventoryForOrder(items, referenceId = null, createdBy = null) {
    try {
      const results = await Promise.all(
        items.map(async ({ inventory_item_id, quantity }) => {
          const { data, error } = await supabase.rpc('deduct_inventory_and_log', {
            p_inventory_id: inventory_item_id,
            p_quantity: quantity,
            p_reference_id: referenceId,
            p_created_by: createdBy
          })
          if (error) {
            console.error(`Inventory deduct error for id ${inventory_item_id}:`, error)
            return { success: false, error: error.message }
          }
          return { success: true }
        })
      )
      const failed = results.filter(r => !r.success)
      if (failed.length > 0) {
        console.error('Some inventory deductions failed:', failed)
      }
      return { success: true }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Book an inward stock entry — adds quantity + logs to ledger atomically
  async bookInward(inventory_item_id, quantity, notes, created_by) {
    try {
      const { data, error } = await supabase.rpc('book_inward', {
        p_inventory_id: inventory_item_id,
        p_quantity: parseFloat(quantity),
        p_notes: notes || null,
        p_created_by: created_by || null
      })
      if (error) return { success: false, error: error.message }
      return { success: true, result: data }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Log a manual quantity adjustment (fire-and-forget, non-fatal)
  async addManualAdjustmentLog(inventory_item_id, qty_before, qty_after, created_by) {
    try {
      const { data: item, error: fetchError } = await supabase
        .from('inventory')
        .select('item_code, item_name')
        .eq('id', inventory_item_id)
        .single()

      if (fetchError) {
        console.warn('addManualAdjustmentLog: could not fetch item details', fetchError)
        return { success: false, error: fetchError.message }
      }

      const { error } = await supabase
        .from('inventory_ledger')
        .insert([{
          inventory_item_id,
          item_code: item.item_code,
          item_name: item.item_name,
          transaction_type: 'manual_adjustment',
          quantity_change: qty_after - qty_before,
          quantity_before: qty_before,
          quantity_after: qty_after,
          reference_type: 'manual',
          reference_id: null,
          notes: null,
          created_by: created_by || null
        }])

      if (error) return { success: false, error: error.message }
      return { success: true }
    } catch (error) {
      return { success: false, error: error.message }
    }
  },

  // Fetch ledger entries with optional filters + server-side pagination
  async getLedgerEntries(filters = {}) {
    try {
      let query = supabase
        .from('inventory_ledger')
        .select('*', { count: 'exact' })
        .order('created_at', { ascending: false })

      if (filters.inventory_item_id) {
        query = query.eq('inventory_item_id', filters.inventory_item_id)
      }
      if (filters.transaction_type) {
        query = query.eq('transaction_type', filters.transaction_type)
      }
      if (filters.search && filters.search.trim()) {
        const term = filters.search.trim()
        query = query.or(`item_name.ilike.%${term}%,item_code.ilike.%${term}%`)
      }
      if (filters.dateFrom) {
        query = query.gte('created_at', filters.dateFrom + 'T00:00:00.000Z')
      }
      if (filters.dateTo) {
        query = query.lte('created_at', filters.dateTo + 'T23:59:59.999Z')
      }
      if (filters.page !== undefined && filters.pageSize !== undefined) {
        const from = (filters.page - 1) * filters.pageSize
        const to   = from + filters.pageSize - 1
        query = query.range(from, to)
      }

      const { data, error, count } = await query
      if (error) return { success: false, error: error.message }
      return { success: true, entries: data || [], count: count || 0 }
    } catch (error) {
      return { success: false, error: error.message }
    }
  }
}
